### ISSUE TITLE
Where is with_threads() ?

### ISSUE THREAD

**Issue by HyeokSuLee** [borntyping/rust-simple_logger#78]
Example 'threads' doesn't support anymore?

**Comment by borntyping** [comment]
Make sure you have the `threads` feature enabled.

You need a section like this in your `Cargo.toml`.

```toml
[dependencies.simple_logger]
features = ["threads"]
```
